### ISSUE TITLE
Not parsed in Widgets

### ISSUE THREAD

**Issue by tedr56** [a5mith/nodebb-plugin-youtube-lite#7]
If writing a youtube link in a widget, the links isn't parsed.

**Comment by a5mith** [comment]
Wow, I missed this by months. That's because it uses the parse.post hook. I don't know if there's a widget hook you can add. In widgets you can use html though, so may be easier to just use the following in your widget. 

`<div class="js-lazyYT" data-youtube-id="ID HERE" data-width="640" data-height="360"><iframe class="lazytube" src="//www.youtube.com/embed/ID HERE"></iframe></div>`
